export const ADD_COUNTRIES = "ADD_COUNTRIES";
export const ADD_COUNTRIES_BY_NAME = "ADD_COUNTRIES_BY_NAME";
export const ADD_COUNTRY_BY_ID = "ADD_COUNTRY_BY_ID";
export const ADD_COUNTRIES_TO_FORM = "ADD_COUNTRIES_TO_FORM";
export const ACTIVITY_CREATION = "ACTIVITY_CREATION";
